# Generated by Django 5.0 on 2024-03-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_medida', models.DateField()),
                ('peitoral', models.IntegerField()),
                ('braco_esq', models.IntegerField()),
                ('braco_dir', models.IntegerField()),
                ('antebraco_esq', models.IntegerField()),
                ('antebraco_dir', models.IntegerField()),
                ('gluteos', models.IntegerField()),
                ('coxa_esq', models.IntegerField()),
                ('coxa_dir', models.IntegerField()),
                ('abdomen', models.IntegerField()),
                ('pantu_esq', models.IntegerField()),
                ('pantu_dir', models.IntegerField()),
            ],
        ),
    ]
