# Generated by Django 5.0 on 2024-04-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino_academia', '0002_pernas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_treino', models.DateField()),
                ('barra', models.CharField(blank=True, max_length=100)),
                ('pulley_frontal', models.CharField(blank=True, max_length=100)),
                ('remada_baixa', models.CharField(blank=True, max_length=100)),
                ('remada_cur', models.CharField(blank=True, max_length=100)),
                ('pull_aro', models.CharField(blank=True, max_length=100)),
                ('remada_uni', models.CharField(blank=True, max_length=100)),
                ('crucifixo_inv', models.CharField(blank=True, max_length=100)),
                ('remada_cav', models.CharField(blank=True, max_length=100)),
                ('pull_down', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'Treino_Costas',
            },
        ),
    ]
